/**
 * The AST — mdast, natively.
 *
 * Node `type` names and fields follow mdast (https://github.com/syntax-tree/mdast)
 * so a tree from `@sigx/markdown` is a valid input for `remark` tooling and a
 * `remark` tree renders here unchanged. The types are hand-written (no
 * `@types/mdast` dependency leaks to consumers) and proved structurally
 * assignable to mdast in `__tests__/ast/mdast.test-d.ts`.
 *
 * Two sigx extensions, both optional so foreign trees stay assignable:
 *  - `key` on every block-level node — the stable reconciliation key the
 *    incremental engine assigns (`b-<i>` at the top level, `<parent>.<i>`
 *    below), so a finalized block never remounts while text streams in.
 *  - `Code.open` — present (`true`) only while a fenced code block is still
 *    unterminated (streaming); absent on a closed fence so a finished tree is
 *    byte-identical to mdast.
 *
 * `position` is unist's: 1-based `line`/`column`, 0-based `offset` into the
 * line-ending-normalised source (CRLF/CR → LF). Tabs are never expanded, so
 * offsets are exact.
 *
 * Plugins add node types by interface merging (the mdast `RootContentMap`
 * pattern): `declare module '@sigx/markdown' { interface PhrasingContentMap
 * { mention: Mention } }` makes `mention` a member of `PhrasingContent`.
 */

// ---------------------------------------------------------------------------
// unist
// ---------------------------------------------------------------------------

/** A point in the source: 1-based line/column, 0-based offset. */
export interface Point {
    line: number;
    column: number;
    offset: number;
}

/** Where a node starts (inclusive) and ends (exclusive) in the source. */
export interface Position {
    start: Point;
    end: Point;
}

/** Free-form ecosystem info a node may carry. */
export interface Data {
    [key: string]: unknown;
}

export interface Node {
    type: string;
    data?: Data;
    position?: Position;
}

export interface Parent extends Node {
    children: Node[];
}

export interface Literal extends Node {
    value: string;
}

/**
 * sigx extension: the stable reconciliation key of a block-level node.
 * Assigned by the parser; regenerated by `assignKeys()`; stripped by
 * `toJSON()`.
 */
export interface Keyed {
    key?: string;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

export interface RootData extends Data {
    /** JSON document format version (see `CURRENT_VERSION`). */
    version?: number;
    /** The id of the format the document was parsed from (`toJSON({ format })`). */
    format?: string;
}

export interface Root extends Parent {
    type: 'root';
    /** Block-level children only (the parser never puts phrasing content at the root). */
    children: BlockContent[];
    data?: RootData;
}

// ---------------------------------------------------------------------------
// Block content
// ---------------------------------------------------------------------------

export interface Paragraph extends Parent, Keyed {
    type: 'paragraph';
    children: PhrasingContent[];
}

export type HeadingDepth = 1 | 2 | 3 | 4 | 5 | 6;

export interface Heading extends Parent, Keyed {
    type: 'heading';
    depth: HeadingDepth;
    children: PhrasingContent[];
}

export interface ThematicBreak extends Node, Keyed {
    type: 'thematicBreak';
}

export interface Blockquote extends Parent, Keyed {
    type: 'blockquote';
    children: BlockContent[];
}

export interface List extends Parent, Keyed {
    type: 'list';
    ordered?: boolean | null;
    /** Starting number of an ordered list. */
    start?: number | null;
    /** `true` when the list is loose (items separated by blank lines). */
    spread?: boolean | null;
    children: ListItem[];
}

export interface ListItem extends Parent, Keyed {
    type: 'listItem';
    /** GFM task item state; `null`/absent when not a task item. */
    checked?: boolean | null;
    spread?: boolean | null;
    children: BlockContent[];
}

export interface Code extends Literal, Keyed {
    type: 'code';
    lang?: string | null;
    meta?: string | null;
    /**
     * sigx extension: `true` only while the fence is unterminated (the source
     * is still streaming). Absent once the closing fence has arrived.
     */
    open?: true;
}

export interface Html extends Literal, Keyed {
    type: 'html';
}

export interface Definition extends Node, Keyed {
    type: 'definition';
    /** Normalised label (case-folded, whitespace-collapsed). */
    identifier: string;
    /** The label as written. */
    label?: string | null;
    url: string;
    title?: string | null;
}

export type AlignType = 'left' | 'right' | 'center' | null;

export interface Table extends Parent, Keyed {
    type: 'table';
    align?: AlignType[] | null;
    /** The first row is the header row. */
    children: TableRow[];
}

export interface TableRow extends Parent, Keyed {
    type: 'tableRow';
    children: TableCell[];
}

export interface TableCell extends Parent, Keyed {
    type: 'tableCell';
    children: PhrasingContent[];
}

// ---------------------------------------------------------------------------
// Phrasing content
// ---------------------------------------------------------------------------

export interface Text extends Literal {
    type: 'text';
}

export interface Emphasis extends Parent {
    type: 'emphasis';
    children: PhrasingContent[];
}

export interface Strong extends Parent {
    type: 'strong';
    children: PhrasingContent[];
}

/** GFM strikethrough. */
export interface Delete extends Parent {
    type: 'delete';
    children: PhrasingContent[];
}

export interface InlineCode extends Literal {
    type: 'inlineCode';
}

/** A hard line break. */
export interface Break extends Node {
    type: 'break';
}

export interface LinkData extends Data {
    /** Set on links produced from `<…>` and bare GFM autolinks. */
    autolink?: boolean;
}

export interface Link extends Parent {
    type: 'link';
    url: string;
    title?: string | null;
    children: PhrasingContent[];
    data?: LinkData;
}

export interface Image extends Node {
    type: 'image';
    url: string;
    title?: string | null;
    alt?: string | null;
}

export type ReferenceType = 'shortcut' | 'collapsed' | 'full';

export interface LinkReference extends Parent {
    type: 'linkReference';
    identifier: string;
    label?: string | null;
    referenceType: ReferenceType;
    children: PhrasingContent[];
}

export interface ImageReference extends Node {
    type: 'imageReference';
    identifier: string;
    label?: string | null;
    referenceType: ReferenceType;
    alt?: string | null;
}

// ---------------------------------------------------------------------------
// Registries (plugins merge into these)
// ---------------------------------------------------------------------------

/** Block-level node types, keyed by `type`. Plugins extend it by interface merging. */
export interface BlockContentMap {
    paragraph: Paragraph;
    heading: Heading;
    thematicBreak: ThematicBreak;
    blockquote: Blockquote;
    list: List;
    code: Code;
    html: Html;
    definition: Definition;
    table: Table;
}

/** Inline node types, keyed by `type`. Plugins extend it by interface merging. */
export interface PhrasingContentMap {
    text: Text;
    emphasis: Emphasis;
    strong: Strong;
    delete: Delete;
    inlineCode: InlineCode;
    break: Break;
    link: Link;
    image: Image;
    linkReference: LinkReference;
    imageReference: ImageReference;
}

export type BlockContent = BlockContentMap[keyof BlockContentMap];
export type PhrasingContent = PhrasingContentMap[keyof PhrasingContentMap];

/** Everything that can appear below the root. */
export type RootContent = BlockContent | ListItem | TableRow | TableCell | PhrasingContent;

/** Every node type in a tree, including the root. */
export type MarkdownNode = Root | RootContent;

/** Nodes that carry a reconciliation key. */
export type KeyedNode = BlockContent | ListItem | TableRow | TableCell;
